@ File generated by m4a2s Voicegroup-Module
	.include "VoiceDef.s"

	.section .rodata
	.global	bank_045
	.align	2

bank_045:

@**************** Voice 000 ****************@

	.byte	ASquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 3, 1, 0

@**************** Voice 001 ****************@

	.byte	AProgNoise
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	FineNoise
	.byte	0, 4, 0, 0

@**************** Voice 002 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_091
	.byte	255, 0, 255, 0

@**************** Voice 003 ****************@

	.byte	AProgNoise
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	RoughNoise
	.byte	0, 0, 12, 0

@**************** Voice 004 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_099
	.byte	64, 0, 255, 0

@**************** Voice 005 ****************@

	.byte	ProgNoise
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	FineNoise
	.byte	0, 1, 9, 3

@**************** Voice 006 ****************@

	.byte	AProgNoise
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	FineNoise
	.byte	0, 0, 15, 0

@**************** Voice 007 ****************@

	.byte	AProgNoise
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	RoughNoise
	.byte	0, 2, 0, 0

@**************** Voice 008 ****************@

	.byte	ASquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 0, 15, 3

@**************** Voice 009 ****************@

	.byte	ProgNoise
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	FineNoise
	.byte	1, 2, 9, 3

@**************** Voice 010 ****************@

	.byte	ASquareWave1
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	WaveDuty50
	.byte	0, 6, 1, 0

@**************** Voice 011 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_128
	.byte	255, 0, 255, 0

@**************** Voice 012 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_129
	.byte	255, 0, 255, 0

@**************** Voice 013 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_130
	.byte	255, 0, 255, 0

@**************** Voice 014 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_131
	.byte	255, 0, 255, 0

@**************** Voice 015 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	0x00
	.word	wave_132
	.byte	255, 0, 255, 0

	.end
