@ File generated by m4a2s Voicegroup-Module
	.include "VoiceDef.s"

	.section .rodata
	.global	drums_000
	.align	2

drums_000:

@**************** Voice 000 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0xC0
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 001 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_004
	.byte	255, 0, 255, 0

@**************** Voice 002 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_005
	.byte	255, 0, 255, 0

@**************** Voice 003 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_006
	.byte	255, 0, 255, 0

@**************** Voice 004 ****************@

	.byte	DirectSound
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_007
	.byte	255, 0, 255, 0

@**************** Voice 005 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0xC0
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 006 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0xC0
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 007 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0xC0
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 008 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0xC0
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 009 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0xC0
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 010 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0xC0
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 011 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0xC0
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 012 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0xC0
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 013 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_008
	.byte	255, 0, 255, 0

@**************** Voice 014 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_009
	.byte	255, 0, 255, 0

@**************** Voice 015 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_008
	.byte	255, 0, 255, 0

@**************** Voice 016 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_010
	.byte	255, 0, 255, 0

@**************** Voice 017 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_011
	.byte	255, 0, 255, 0

@**************** Voice 018 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_012
	.byte	255, 0, 255, 0

@**************** Voice 019 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0xC0
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 020 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0xC0
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 021 ****************@

	.byte	DirectSound
	.byte	An2 
	.byte	0x00
	.byte	c_v-30
	.word	wave_013
	.byte	255, 0, 255, 0

@**************** Voice 022 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0xC0
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 023 ****************@

	.byte	DirectSound
	.byte	Bn2 
	.byte	0x00
	.byte	c_v-30
	.word	wave_013
	.byte	255, 0, 255, 0

@**************** Voice 024 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_007
	.byte	255, 0, 255, 0

@**************** Voice 025 ****************@

	.byte	DirectSound
	.byte	Cs3 
	.byte	0x00
	.byte	c_v-30
	.word	wave_013
	.byte	255, 0, 255, 0

@**************** Voice 026 ****************@

	.byte	DirectSound
	.byte	Ds3 
	.byte	0x00
	.byte	c_v-30
	.word	wave_013
	.byte	255, 0, 255, 0

@**************** Voice 027 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0xC0
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 028 ****************@

	.byte	DirectSound
	.byte	Fn3 
	.byte	0x00
	.byte	c_v-30
	.word	wave_013
	.byte	255, 0, 255, 0

@**************** Voice 029 ****************@

	.byte	DirectSound
	.byte	Ds4 
	.byte	0x00
	.byte	c_v-30
	.word	wave_013
	.byte	255, 0, 255, 0

@**************** Voice 030 ****************@

	.byte	DirectSound
	.byte	Fn3 
	.byte	0x00
	.byte	c_v-25
	.word	wave_014
	.byte	255, 0, 255, 0

@**************** Voice 031 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_014
	.byte	255, 0, 255, 0

@**************** Voice 032 ****************@

	.byte	DirectSound
	.byte	Fn3 
	.byte	0x00
	.byte	c_v+25
	.word	wave_015
	.byte	255, 0, 255, 0

@**************** Voice 033 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_015
	.byte	255, 0, 255, 0

@**************** Voice 034 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+20
	.word	wave_016
	.byte	255, 0, 255, 0

@**************** Voice 035 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+20
	.word	wave_017
	.byte	255, 0, 255, 0

@**************** Voice 036 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_018
	.byte	255, 0, 255, 0

@**************** Voice 037 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_019
	.byte	255, 0, 255, 0

@**************** Voice 038 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_020
	.byte	255, 0, 255, 0

@**************** Voice 039 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+20
	.word	wave_021
	.byte	255, 0, 255, 0

@**************** Voice 040 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_022
	.byte	255, 0, 255, 0

@**************** Voice 041 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+20
	.word	wave_023
	.byte	255, 0, 255, 0

@**************** Voice 042 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v-30
	.word	wave_013
	.byte	255, 0, 255, 0

@**************** Voice 043 ****************@

	.byte	DirectSoundFix
	.byte	Dn3 
	.byte	0x00
	.byte	c_v+10
	.word	wave_023
	.byte	255, 0, 255, 0

@**************** Voice 044 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v-30
	.word	wave_013
	.byte	255, 0, 255, 0

@**************** Voice 045 ****************@

	.byte	DirectSound
	.byte	Fn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_023
	.byte	255, 0, 255, 0

@**************** Voice 046 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v-30
	.word	wave_024
	.byte	255, 0, 255, 0

@**************** Voice 047 ****************@

	.byte	DirectSound
	.byte	Gs3 
	.byte	0x00
	.byte	c_v-25
	.word	wave_023
	.byte	255, 0, 255, 0

@**************** Voice 048 ****************@

	.byte	DirectSound
	.byte	Bn3 
	.byte	0x00
	.byte	c_v-20
	.word	wave_023
	.byte	255, 0, 255, 0

@**************** Voice 049 ****************@

	.byte	DirectSound
	.byte	As2 
	.byte	0x00
	.byte	c_v+30
	.word	wave_025
	.byte	255, 0, 255, 0

@**************** Voice 050 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0xC0
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 051 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0xC0
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 052 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0xC0
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 053 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0xC0
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 054 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_026
	.byte	255, 0, 255, 0

@**************** Voice 055 ****************@

	.byte	DirectSound
	.byte	Bn3 
	.byte	0x00
	.byte	c_v-30
	.word	wave_025
	.byte	255, 0, 255, 0

@**************** Voice 056 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v-25
	.word	wave_027
	.byte	255, 0, 255, 0

@**************** Voice 057 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v-30
	.word	wave_025
	.byte	255, 0, 255, 0

@**************** Voice 058 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0xC0
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 059 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v-30
	.word	wave_025
	.byte	255, 0, 255, 0

@**************** Voice 060 ****************@

	.byte	DirectSound
	.byte	Fn3 
	.byte	0x00
	.byte	c_v+25
	.word	wave_028
	.byte	255, 0, 255, 0

@**************** Voice 061 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_028
	.byte	255, 0, 255, 0

@**************** Voice 062 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+25
	.word	wave_029
	.byte	255, 0, 255, 0

@**************** Voice 063 ****************@

	.byte	DirectSound
	.byte	An3 
	.byte	0x00
	.byte	c_v+25
	.word	wave_030
	.byte	255, 0, 255, 0

@**************** Voice 064 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_030
	.byte	255, 0, 255, 0

@**************** Voice 065 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v-25
	.word	wave_031
	.byte	255, 0, 255, 0

@**************** Voice 066 ****************@

	.byte	DirectSound
	.byte	Dn2 
	.byte	0x00
	.byte	c_v+0
	.word	wave_031
	.byte	255, 0, 255, 0

@**************** Voice 067 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+25
	.word	wave_014
	.byte	255, 0, 255, 0

@**************** Voice 068 ****************@

	.byte	DirectSound
	.byte	Gn2 
	.byte	0x00
	.byte	c_v+0
	.word	wave_014
	.byte	255, 0, 255, 0

@**************** Voice 069 ****************@

	.byte	ProgNoise
	.byte	Cn4 
	.byte	0x00
	.byte	0xC0
	.word	FineNoise
	.byte	0, 1, 3, 1

@**************** Voice 070 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0xC0
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 071 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+30
	.word	wave_032
	.byte	255, 0, 255, 0

@**************** Voice 072 ****************@

	.byte	DirectSound
	.byte	Gn2 
	.byte	0x00
	.byte	c_v-30
	.word	wave_032
	.byte	255, 0, 255, 0

@**************** Voice 073 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0xC0
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 074 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0xC0
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 075 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_033
	.byte	255, 0, 255, 0

@**************** Voice 076 ****************@

	.byte	DirectSound
	.byte	An2 
	.byte	0x00
	.byte	c_v+0
	.word	wave_034
	.byte	255, 0, 255, 0

@**************** Voice 077 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_034
	.byte	255, 0, 255, 0

@**************** Voice 078 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+15
	.word	wave_035
	.byte	255, 0, 255, 0

@**************** Voice 079 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v-15
	.word	wave_036
	.byte	255, 0, 255, 0

@**************** Voice 080 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0xC0
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 081 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0xC0
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 082 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0xC0
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 083 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+15
	.word	wave_037
	.byte	255, 0, 255, 0

@**************** Voice 084 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0x80
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 085 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0x80
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 086 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0x80
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 087 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0x80
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 088 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0x80
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 089 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0x80
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 090 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0x80
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 091 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0x80
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 092 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0x80
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 093 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0x80
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 094 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0x80
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 095 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0x80
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 096 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0x80
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 097 ****************@

	.byte	ProgNoise
	.byte	An3 
	.byte	0x00
	.byte	0xFF
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 098 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x04
	.byte	0xC0
	.word	FineNoise
	.byte	0, 0, 15, 0

@**************** Voice 099 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0xC0
	.word	FineNoise
	.byte	0, 0, 15, 0

@**************** Voice 100 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0x80
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 101 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0xC0
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 102 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0xFF
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 103 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+25
	.word	wave_038
	.byte	255, 0, 255, 0

@**************** Voice 104 ****************@

	.byte	DirectSound
	.byte	Fn2 
	.byte	0x00
	.byte	c_v+0
	.word	wave_039
	.byte	255, 0, 255, 0

@**************** Voice 105 ****************@

	.byte	DirectSound
	.byte	Fs2 
	.byte	0x00
	.byte	c_v+0
	.word	wave_039
	.byte	255, 0, 255, 0

@**************** Voice 106 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0x80
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 107 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+25
	.word	wave_040
	.byte	255, 0, 255, 0

@**************** Voice 108 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v-20
	.word	wave_041
	.byte	255, 0, 255, 0

@**************** Voice 109 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0x80
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 110 ****************@

	.byte	DirectSound
	.byte	Bn2 
	.byte	0x00
	.byte	c_v+0
	.word	wave_039
	.byte	255, 0, 255, 0

@**************** Voice 111 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_039
	.byte	255, 0, 255, 0

@**************** Voice 112 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0x80
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 113 ****************@

	.byte	DirectSound
	.byte	Dn3 
	.byte	0x00
	.byte	c_v+0
	.word	wave_039
	.byte	255, 0, 255, 0

@**************** Voice 114 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0xC0
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 115 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0xC0
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 116 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v+20
	.word	wave_042
	.byte	255, 0, 255, 0

@**************** Voice 117 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0xC0
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 118 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0xC0
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 119 ****************@

	.byte	ProgNoise
	.byte	Gs4 
	.byte	0x00
	.byte	0xC0
	.word	FineNoise
	.byte	0, 0, 7, 0

@**************** Voice 120 ****************@

	.byte	DirectSoundFix
	.byte	Cn3 
	.byte	0x00
	.byte	c_v-20
	.word	wave_043
	.byte	255, 0, 255, 0
	
	.end
