@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_390_grp, bank_045
	.equ	seq_390_pri, 30
	.equ	seq_390_rev, 0
	.equ	seq_390_mvl, 127
	.equ	seq_390_key, 0

	.section .rodata
	.global	seq_390
	.align	2

@*********************** Track 01 ***********************@

seq_390_0:
	.byte	KEYSH , seq_390_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 15
	.byte		VOL   , 110*seq_390_mvl/mxv
	.byte		MOD   , 0
	.byte		BENDR , 2
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+0
	.byte		N07   , En3 , v127
	.byte	W07
	.byte		        Ds3 
	.byte	W07
	.byte		        En3 
	.byte	W07
	.byte		        Ds3 
	.byte	W07
	.byte		N56
	.byte	W56
	.byte	FINE

@******************************************************@

	.align	2

seq_390:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_390_pri	@ Priority
	.byte	seq_390_rev	@ Reverb

	.word	seq_390_grp

	.word	seq_390_0

	.end
