@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_287_grp, bank_013
	.equ	seq_287_pri, 100
	.equ	seq_287_rev, 0
	.equ	seq_287_mvl, 127
	.equ	seq_287_key, 0

	.section .rodata
	.global	seq_287
	.align	2

@*********************** Track 01 ***********************@

seq_287_0:
	.byte	KEYSH , seq_287_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 7
	.byte		VOL   , 100*seq_287_mvl/mxv
	.byte		BEND  , c_v+0
	.byte		N48   , Gs3 , v127
	.byte	W24
	.byte	W24
	.byte	FINE

@******************************************************@

	.align	2

seq_287:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_287_pri	@ Priority
	.byte	seq_287_rev	@ Reverb

	.word	seq_287_grp

	.word	seq_287_0

	.end
