@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_138_grp, bank_044
	.equ	seq_138_pri, 10
	.equ	seq_138_rev, 0
	.equ	seq_138_mvl, 127
	.equ	seq_138_key, 0

	.section .rodata
	.global	seq_138
	.align	2

@*********************** Track 01 ***********************@

seq_138_0:
	.byte		VOL   , 110*seq_138_mvl/mxv
	.byte	KEYSH , seq_138_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 67
	.byte		N42   , Cn3 , v127
	.byte	W96
	.byte	W96
	.byte	FINE

@******************************************************@

	.align	2

seq_138:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_138_pri	@ Priority
	.byte	seq_138_rev	@ Reverb

	.word	seq_138_grp

	.word	seq_138_0

	.end
