@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_195_grp, bank_044
	.equ	seq_195_pri, 10
	.equ	seq_195_rev, 0
	.equ	seq_195_mvl, 127
	.equ	seq_195_key, 0

	.section .rodata
	.global	seq_195
	.align	2

@*********************** Track 01 ***********************@

seq_195_0:
	.byte	KEYSH , seq_195_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 76
	.byte		VOL   , 70*seq_195_mvl/mxv
	.byte		N05   , En5 , v127
	.byte	W05
	.byte		        Bn5 
	.byte	W05
	.byte		        An5 
	.byte	W05
	.byte		        Bn5 
	.byte	W05
	.byte		N09   , En6 
	.byte	W04
	.byte	W24
	.byte	FINE

@*********************** Track 02 ***********************@

seq_195_1:
	.byte	KEYSH , seq_195_key+0
	.byte		VOICE , 77
	.byte		VOL   , 44*seq_195_mvl/mxv
	.byte		PAN   , c_v+0
	.byte		N05   , En5 , v127
	.byte	W05
	.byte		        Bn5 
	.byte	W05
	.byte		        An5 
	.byte	W05
	.byte		        Bn5 
	.byte	W05
	.byte		N09   , En6 
	.byte	W04
	.byte	W24
	.byte	FINE

@******************************************************@

	.align	2

seq_195:
	.byte	2	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_195_pri	@ Priority
	.byte	seq_195_rev	@ Reverb

	.word	seq_195_grp

	.word	seq_195_0
	.word	seq_195_1

	.end
