@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_158_grp, bank_044
	.equ	seq_158_pri, 40
	.equ	seq_158_rev, 0
	.equ	seq_158_mvl, 127
	.equ	seq_158_key, 0

	.section .rodata
	.global	seq_158
	.align	2

@*********************** Track 01 ***********************@

seq_158_0:
	.byte		VOL   , 90*seq_158_mvl/mxv
	.byte	KEYSH , seq_158_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 110
	.byte		BENDR , 10
	.byte		BEND  , c_v-63
	.byte		N42   , Fn3 , v127
	.byte	W01
	.byte		BEND  , c_v-58
	.byte	W01
	.byte		        c_v-53
	.byte	W01
	.byte		        c_v-43
	.byte	W01
	.byte		        c_v-36
	.byte	W01
	.byte		        c_v-29
	.byte	W01
	.byte		        c_v-20
	.byte	W01
	.byte		        c_v-11
	.byte	W01
	.byte		        c_v+0
	.byte	W01
	.byte		        c_v+7
	.byte	W01
	.byte		        c_v+15
	.byte	W01
	.byte		        c_v+31
	.byte	W01
	.byte		        c_v+46
	.byte	W01
	.byte		        c_v+54
	.byte	W01
	.byte		        c_v+46
	.byte	W01
	.byte		        c_v+31
	.byte	W01
	.byte		        c_v+15
	.byte	W01
	.byte		        c_v-12
	.byte	W01
	.byte		        c_v-28
	.byte	W01
	.byte		        c_v-43
	.byte	W01
	.byte		        c_v-51
	.byte	W01
	.byte		        c_v-43
	.byte	W01
	.byte		        c_v-28
	.byte	W01
	.byte		        c_v-12
	.byte	W01
	.byte		        c_v+7
	.byte	W01
	.byte		        c_v+23
	.byte	W01
	.byte		        c_v+39
	.byte	W01
	.byte		        c_v+46
	.byte	W01
	.byte		        c_v+39
	.byte	W01
	.byte		        c_v+23
	.byte	W01
	.byte		        c_v+7
	.byte	W01
	.byte		        c_v-6
	.byte	W01
	.byte		        c_v-20
	.byte	W01
	.byte		        c_v-36
	.byte	W01
	.byte		        c_v-43
	.byte	W01
	.byte		        c_v-36
	.byte	W01
	.byte		        c_v-20
	.byte	W01
	.byte		        c_v-6
	.byte	W01
	.byte		        c_v+3
	.byte	W01
	.byte		        c_v+15
	.byte	W01
	.byte		        c_v+31
	.byte	W01
	.byte		        c_v+15
	.byte	W01
	.byte		        c_v+0
	.byte	W06
	.byte	FINE

@******************************************************@

	.align	2

seq_158:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_158_pri	@ Priority
	.byte	seq_158_rev	@ Reverb

	.word	seq_158_grp

	.word	seq_158_0

	.end
