@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_271_grp, bank_013
	.equ	seq_271_pri, 100
	.equ	seq_271_rev, 0
	.equ	seq_271_mvl, 127
	.equ	seq_271_key, 0

	.section .rodata
	.global	seq_271
	.align	2

@*********************** Track 01 ***********************@

seq_271_0:
	.byte		VOL   , 110*seq_271_mvl/mxv
	.byte	KEYSH , seq_271_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 30
	.byte		BEND  , c_v+40
	.byte		N05   , As2 , v127
	.byte	W03
	.byte		BEND  , c_v+0
	.byte	W03
	.byte		N24   , Cs3 
	.byte	W18
	.byte	W06
	.byte		BEND  , c_v+40
	.byte		N05   , As2 
	.byte	W03
	.byte		BEND  , c_v+0
	.byte	W03
	.byte		N30   , Cs3 
	.byte	W12
	.byte	W24
	.byte	FINE

@******************************************************@

	.align	2

seq_271:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_271_pri	@ Priority
	.byte	seq_271_rev	@ Reverb

	.word	seq_271_grp

	.word	seq_271_0

	.end
