@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_394_grp, bank_013
	.equ	seq_394_pri, 10
	.equ	seq_394_rev, 0
	.equ	seq_394_mvl, 127
	.equ	seq_394_key, 0

	.section .rodata
	.global	seq_394
	.align	2

@*********************** Track 01 ***********************@

seq_394_0:
	.byte		VOL   , 70*seq_394_mvl/mxv
	.byte	KEYSH , seq_394_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 71
	.byte		N02   , Cn6 , v100
	.byte	W03
	.byte		        En5 
	.byte	W03
	.byte		N03   , Cn5 
	.byte	W04
	.byte		        Gn4 
	.byte	W04
	.byte		N04   , En4 
	.byte	W05
	.byte		N06   , Cn4 
	.byte	W07
	.byte		N12   , Gn3 
	.byte	W13
	.byte		N20   , Ds3 
	.byte	W21
	.byte		N28   , Bn2 
	.byte	W30
	.byte		N42   , Gn2 
	.byte	W06
	.byte	W36
	.byte	W01
	.byte		N56   , Cn2 
	.byte	W56
	.byte	W03
	.byte	FINE

@******************************************************@

	.align	2

seq_394:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_394_pri	@ Priority
	.byte	seq_394_rev	@ Reverb

	.word	seq_394_grp

	.word	seq_394_0

	.end
