@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_197_grp, bank_044
	.equ	seq_197_pri, 20
	.equ	seq_197_rev, 0
	.equ	seq_197_mvl, 127
	.equ	seq_197_key, 0

	.section .rodata
	.global	seq_197
	.align	2

@*********************** Track 01 ***********************@

seq_197_0:
	.byte	KEYSH , seq_197_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 51
	.byte		VOL   , 127*seq_197_mvl/mxv
	.byte		BENDR , 8
	.byte		BEND  , c_v+0
	.byte		N60   , Gs5 , v127
	.byte	W02
	.byte		BEND  , c_v-64
	.byte	W02
	.byte		        c_v+0
	.byte	W02
	.byte		        c_v-64
	.byte	W02
	.byte		        c_v+0
	.byte	W02
	.byte		        c_v-64
	.byte	W02
	.byte		        c_v+0
	.byte	W02
	.byte		        c_v-64
	.byte	W02
	.byte		        c_v+0
	.byte	W02
	.byte		        c_v-64
	.byte	W02
	.byte		        c_v+0
	.byte	W02
	.byte		        c_v-64
	.byte	W02
	.byte		        c_v+0
	.byte	W02
	.byte		        c_v-64
	.byte	W02
	.byte		        c_v+0
	.byte	W02
	.byte		        c_v-64
	.byte	W02
	.byte		        c_v+0
	.byte	W02
	.byte		        c_v-64
	.byte	W02
	.byte		        c_v+0
	.byte	W02
	.byte		        c_v-64
	.byte	W02
	.byte		        c_v+0
	.byte	W02
	.byte		        c_v-64
	.byte	W02
	.byte		        c_v+0
	.byte	W02
	.byte		        c_v-64
	.byte	W02
	.byte		        c_v+0
	.byte	W02
	.byte		        c_v-64
	.byte	W02
	.byte		        c_v+0
	.byte	W02
	.byte		        c_v-64
	.byte	W02
	.byte		        c_v+0
	.byte	W02
	.byte		        c_v-64
	.byte	W14
	.byte	W24
	.byte	W24
	.byte	W24
	.byte	W06
	.byte	GOTO
	 .word	seq_197_0 + 0x2
	.byte	FINE

@******************************************************@

	.align	2

seq_197:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_197_pri	@ Priority
	.byte	seq_197_rev	@ Reverb

	.word	seq_197_grp

	.word	seq_197_0

	.end
