@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_338_grp, bank_013
	.equ	seq_338_pri, 100
	.equ	seq_338_rev, 0
	.equ	seq_338_mvl, 127
	.equ	seq_338_key, 0

	.section .rodata
	.global	seq_338
	.align	2

@*********************** Track 01 ***********************@

seq_338_0:
	.byte	KEYSH , seq_338_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 19
	.byte		VOL   , 105*seq_338_mvl/mxv
	.byte		BEND  , c_v+0
	.byte		N64   , Fs3 , v127
	.byte	W24
	.byte	W24
	.byte	W24
	.byte	FINE

@******************************************************@

	.align	2

seq_338:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_338_pri	@ Priority
	.byte	seq_338_rev	@ Reverb

	.word	seq_338_grp

	.word	seq_338_0

	.end
