@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_242_grp, bank_013
	.equ	seq_242_pri, 100
	.equ	seq_242_rev, 0
	.equ	seq_242_mvl, 127
	.equ	seq_242_key, 0

	.section .rodata
	.global	seq_242
	.align	2

@*********************** Track 01 ***********************@

seq_242_0:
	.byte		VOL   , 110*seq_242_mvl/mxv
	.byte	KEYSH , seq_242_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 3
	.byte		N68   , Cn3 , v127
	.byte	W24
	.byte	W24
	.byte	W24
	.byte	FINE

@******************************************************@

	.align	2

seq_242:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_242_pri	@ Priority
	.byte	seq_242_rev	@ Reverb

	.word	seq_242_grp

	.word	seq_242_0

	.end
