@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_007_grp, bank_005
	.equ	seq_007_pri, 0
	.equ	seq_007_rev, 0
	.equ	seq_007_mvl, 127
	.equ	seq_007_key, 0

	.section .rodata
	.global	seq_007
	.align	2

@*********************** Track 01 ***********************@

seq_007_0:
	.byte	KEYSH , seq_007_key+0
	.byte	TEMPO , 80/2
	.byte		VOICE , 61
	.byte		MOD   , 0
	.byte		VOL   , 82*seq_007_mvl/mxv
	.byte		N06   , Cn4 , v100
	.byte	W06
	.byte		        Bn3 
	.byte	W06
	.byte		        As3 
	.byte	W06
	.byte		        An3 
	.byte	W06
	.byte		        Gs3 
	.byte	W12
	.byte		        Gn3 
	.byte	W12
	.byte		N96   , Fs3 
	.byte	W06
	.byte		MOD   , 24
	.byte	W42
	.byte	W96
	.byte	FINE

@*********************** Track 02 ***********************@

seq_007_1:
	.byte	KEYSH , seq_007_key+0
	.byte		VOICE , 61
	.byte		VOL   , 82*seq_007_mvl/mxv
	.byte		MOD   , 0
	.byte		N06   , Gn3 , v100
	.byte	W06
	.byte		        Fs3 
	.byte	W06
	.byte		        Fn3 
	.byte	W06
	.byte		        En3 
	.byte	W06
	.byte		        Ds3 
	.byte	W12
	.byte		        Dn3 
	.byte	W12
	.byte		N96   , Cs3 
	.byte	W10
	.byte		MOD   , 24
	.byte	W36
	.byte	W02
	.byte	W96
	.byte	FINE

@*********************** Track 03 ***********************@

seq_007_2:
	.byte	KEYSH , seq_007_key+0
	.byte		VOICE , 34
	.byte		MOD   , 0
	.byte		VOL   , 105*seq_007_mvl/mxv
	.byte		N06   , En1 , v100
	.byte	W06
	.byte		        Ds1 
	.byte	W06
	.byte		        Dn1 
	.byte	W06
	.byte		        Cs1 
	.byte	W06
	.byte		        Cn1 
	.byte	W12
	.byte		        Bn0 
	.byte	W12
	.byte		BEND  , c_v-53
	.byte		N96   , As0 
	.byte	W01
	.byte		BEND  , c_v-43
	.byte	W01
	.byte		        c_v-34
	.byte	W01
	.byte		        c_v-19
	.byte	W01
	.byte		        c_v-13
	.byte	W01
	.byte		        c_v-8
	.byte	W01
	.byte		        c_v-2
	.byte	W01
	.byte		        c_v-1
	.byte	W01
	.byte		        c_v+0
	.byte	W04
	.byte		MOD   , 24
	.byte	W36
	.byte	W96
	.byte	FINE

@*********************** Track 04 ***********************@

seq_007_3:
	.byte		VOL   , 105*seq_007_mvl/mxv
	.byte	KEYSH , seq_007_key+0
	.byte		VOICE , 127
	.byte		N24   , An2 , v127
	.byte	W56
	.byte	W01
	.byte		N06   , En4 , v100
	.byte	W15
	.byte		N06
	.byte	W12
	.byte		N06
	.byte	W10
	.byte		        En4 , v080
	.byte	W02
	.byte	W06
	.byte		N05   , En4 , v072
	.byte	W07
	.byte		N05
	.byte	W07
	.byte		N04   , En4 , v076
	.byte	W06
	.byte		N04
	.byte	W05
	.byte		N03
	.byte	W04
	.byte		N02   , En4 , v084
	.byte	W03
	.byte		        En4 , v088
	.byte	W03
	.byte		        En4 , v100
	.byte	W03
	.byte		N02
	.byte	W02
	.byte		N02
	.byte	W02
	.byte		N06   , Gs2 , v127
	.byte		N04   , Gn4 , v080
	.byte	W04
	.byte		N05   , Fs4 , v092
	.byte	W44
	.byte	FINE

@******************************************************@

	.align	2

seq_007:
	.byte	4	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_007_pri	@ Priority
	.byte	seq_007_rev	@ Reverb

	.word	seq_007_grp

	.word	seq_007_0
	.word	seq_007_1
	.word	seq_007_2
	.word	seq_007_3

	.end
