@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_144_grp, bank_044
	.equ	seq_144_pri, 30
	.equ	seq_144_rev, 0
	.equ	seq_144_mvl, 127
	.equ	seq_144_key, 0

	.section .rodata
	.global	seq_144
	.align	2

@*********************** Track 01 ***********************@

seq_144_0:
	.byte		VOL   , 50*seq_144_mvl/mxv
	.byte	KEYSH , seq_144_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 43
	.byte		N05   , Fs4 , v127
	.byte	W05
	.byte		        An3 
	.byte	W05
	.byte		        Dn4 , v112
	.byte	W05
	.byte		        Fs3 , v092
	.byte	W05
	.byte		        An3 , v064
	.byte	W05
	.byte		        Fs3 , v040
	.byte	W23
	.byte	FINE

@*********************** Track 02 ***********************@

seq_144_1:
	.byte	KEYSH , seq_144_key+0
	.byte		VOL   , 19*seq_144_mvl/mxv
	.byte	W10
	.byte		N05   , Fs4 , v127
	.byte	W02
	.byte		VOICE , 41
	.byte	W03
	.byte		N05   , An3 
	.byte	W05
	.byte		        Dn4 , v112
	.byte	W05
	.byte		        Fs3 , v092
	.byte	W05
	.byte		        An3 , v064
	.byte	W05
	.byte		        Fs3 , v040
	.byte	W13
	.byte	FINE

@******************************************************@

	.align	2

seq_144:
	.byte	2	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_144_pri	@ Priority
	.byte	seq_144_rev	@ Reverb

	.word	seq_144_grp

	.word	seq_144_0
	.word	seq_144_1

	.end
