@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_374_grp, bank_045
	.equ	seq_374_pri, 70
	.equ	seq_374_rev, 0
	.equ	seq_374_mvl, 127
	.equ	seq_374_key, 0

	.section .rodata
	.global	seq_374
	.align	2

@*********************** Track 01 ***********************@

seq_374_0:
	.byte	KEYSH , seq_374_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 3
	.byte		VOL   , 110*seq_374_mvl/mxv
	.byte		BENDR , 12
	.byte		PAN   , c_v+0
	.byte		BEND  , c_v+0
	.byte		N56   , Gs3 , v052
	.byte	W02
	.byte		BEND  , c_v+39
	.byte	W02
	.byte		        c_v+0
	.byte	W02
	.byte		        c_v+23
	.byte	W02
	.byte		        c_v+0
	.byte	W02
	.byte		        c_v+31
	.byte	W02
	.byte		        c_v+0
	.byte	W02
	.byte		        c_v+15
	.byte	W02
	.byte		VOL   , 97*seq_374_mvl/mxv
	.byte		BEND  , c_v+0
	.byte	W02
	.byte		        c_v+7
	.byte	W02
	.byte		        c_v+0
	.byte	W02
	.byte		        c_v+39
	.byte	W02
	.byte		        c_v+0
	.byte	W02
	.byte		        c_v+15
	.byte	W02
	.byte		        c_v+0
	.byte	W02
	.byte		        c_v+23
	.byte	W02
	.byte		VOL   , 83*seq_374_mvl/mxv
	.byte		BEND  , c_v+0
	.byte	W02
	.byte		        c_v+7
	.byte	W02
	.byte		        c_v+0
	.byte	W02
	.byte		        c_v+31
	.byte	W02
	.byte		        c_v+0
	.byte	W02
	.byte		        c_v+39
	.byte	W02
	.byte		        c_v+0
	.byte	W02
	.byte		        c_v+15
	.byte	W02
	.byte		VOL   , 69*seq_374_mvl/mxv
	.byte		BEND  , c_v+0
	.byte	W02
	.byte		        c_v+31
	.byte	W02
	.byte		        c_v+0
	.byte	W02
	.byte		        c_v+7
	.byte	W02
	.byte		        c_v+0
	.byte	W40
	.byte	FINE

@******************************************************@

	.align	2

seq_374:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_374_pri	@ Priority
	.byte	seq_374_rev	@ Reverb

	.word	seq_374_grp

	.word	seq_374_0

	.end
