@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_400_grp, bank_013
	.equ	seq_400_pri, 10
	.equ	seq_400_rev, 0
	.equ	seq_400_mvl, 127
	.equ	seq_400_key, 0

	.section .rodata
	.global	seq_400
	.align	2

@*********************** Track 01 ***********************@

seq_400_0:
	.byte		VOL   , 70*seq_400_mvl/mxv
	.byte	KEYSH , seq_400_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 71
	.byte		N02   , Fs6 , v100
	.byte	W03
	.byte		        Cs6 
	.byte	W03
	.byte		N03   , Gs5 
	.byte	W04
	.byte		        En5 
	.byte	W04
	.byte		        Cn5 
	.byte	W04
	.byte		        Gs4 
	.byte	W05
	.byte		N04   , Fn4 
	.byte	W01
	.byte	W04
	.byte		N05   , Dn4 
	.byte	W06
	.byte		        Bn3 
	.byte	W07
	.byte		N06   , An3 
	.byte	W07
	.byte		N12   , Gn3 
	.byte	W13
	.byte		N15   , En3 
	.byte	W11
	.byte	W05
	.byte		N17   , Dn3 
	.byte	W19
	.byte		N21   , Bn2 
	.byte	W22
	.byte		N28   , Gs2 
	.byte	W02
	.byte	W24
	.byte	W04
	.byte		N36   , Fn2 
	.byte	W20
	.byte	W20
	.byte		N44   , Dn2 
	.byte	W04
	.byte	W24
	.byte	W20
	.byte		N68   , As1 
	.byte	W04
	.byte	W24
	.byte	W24
	.byte	W24
	.byte	FINE

@******************************************************@

	.align	2

seq_400:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_400_pri	@ Priority
	.byte	seq_400_rev	@ Reverb

	.word	seq_400_grp

	.word	seq_400_0

	.end
