@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_291_grp, bank_013
	.equ	seq_291_pri, 100
	.equ	seq_291_rev, 0
	.equ	seq_291_mvl, 127
	.equ	seq_291_key, 0

	.section .rodata
	.global	seq_291
	.align	2

@*********************** Track 01 ***********************@

seq_291_0:
	.byte	KEYSH , seq_291_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 11
	.byte		VOL   , 100*seq_291_mvl/mxv
	.byte		BEND  , c_v+0
	.byte		N44   , Fs3 , v127
	.byte	W24
	.byte	W24
	.byte	FINE

@******************************************************@

	.align	2

seq_291:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_291_pri	@ Priority
	.byte	seq_291_rev	@ Reverb

	.word	seq_291_grp

	.word	seq_291_0

	.end
