@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_162_grp, bank_043
	.equ	seq_162_pri, 10
	.equ	seq_162_rev, 0
	.equ	seq_162_mvl, 127
	.equ	seq_162_key, 0

	.section .rodata
	.global	seq_162
	.align	2

@*********************** Track 01 ***********************@

seq_162_0:
	.byte	KEYSH , seq_162_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 0
	.byte		BENDR , 15
	.byte		VOL   , 36*seq_162_mvl/mxv
	.byte		BEND  , c_v+0
	.byte		N80   , Ds3 , v127
	.byte	W01
	.byte		VOL   , 45*seq_162_mvl/mxv
	.byte	W01
	.byte		        52*seq_162_mvl/mxv
	.byte	W01
	.byte		        58*seq_162_mvl/mxv
	.byte	W01
	.byte		        63*seq_162_mvl/mxv
	.byte	W01
	.byte		        67*seq_162_mvl/mxv
	.byte	W01
	.byte		        70*seq_162_mvl/mxv
	.byte	W04
	.byte		BEND  , c_v+0
	.byte	W01
	.byte		        c_v-2
	.byte	W01
	.byte		        c_v-4
	.byte	W01
	.byte		        c_v-6
	.byte	W01
	.byte		        c_v-7
	.byte	W01
	.byte		        c_v-9
	.byte	W01
	.byte		        c_v-11
	.byte	W01
	.byte		        c_v-12
	.byte	W01
	.byte		        c_v-14
	.byte	W01
	.byte		        c_v-16
	.byte	W01
	.byte		        c_v-18
	.byte	W01
	.byte		        c_v-19
	.byte	W01
	.byte		        c_v-21
	.byte	W01
	.byte		        c_v-23
	.byte	W01
	.byte		VOL   , 69*seq_162_mvl/mxv
	.byte		BEND  , c_v-8
	.byte	W01
	.byte		        c_v-10
	.byte	W01
	.byte		        c_v-12
	.byte	W01
	.byte		VOL   , 68*seq_162_mvl/mxv
	.byte		BEND  , c_v-14
	.byte	W01
	.byte		        c_v-15
	.byte	W01
	.byte		        c_v-17
	.byte	W01
	.byte		VOL   , 67*seq_162_mvl/mxv
	.byte		BEND  , c_v-19
	.byte	W01
	.byte		        c_v-21
	.byte	W01
	.byte		        c_v-22
	.byte	W01
	.byte		VOL   , 66*seq_162_mvl/mxv
	.byte		BEND  , c_v-24
	.byte	W01
	.byte		        c_v-26
	.byte	W01
	.byte		        c_v-28
	.byte	W01
	.byte		VOL   , 65*seq_162_mvl/mxv
	.byte		BEND  , c_v-29
	.byte	W01
	.byte		        c_v-31
	.byte	W01
	.byte		        c_v-33
	.byte	W01
	.byte		        c_v-16
	.byte	W01
	.byte		VOL   , 63*seq_162_mvl/mxv
	.byte		BEND  , c_v-18
	.byte	W01
	.byte		        c_v-20
	.byte	W01
	.byte		        c_v-23
	.byte	W01
	.byte		VOL   , 63*seq_162_mvl/mxv
	.byte		BEND  , c_v-25
	.byte	W01
	.byte		        c_v-27
	.byte	W01
	.byte		        c_v-29
	.byte	W01
	.byte		VOL   , 62*seq_162_mvl/mxv
	.byte		BEND  , c_v-30
	.byte	W01
	.byte		        c_v-32
	.byte	W01
	.byte		        c_v-34
	.byte	W01
	.byte		VOL   , 61*seq_162_mvl/mxv
	.byte		BEND  , c_v-36
	.byte	W01
	.byte		        c_v-37
	.byte	W01
	.byte		        c_v-39
	.byte	W01
	.byte		VOL   , 60*seq_162_mvl/mxv
	.byte		BEND  , c_v-41
	.byte	W01
	.byte		        c_v-22
	.byte	W01
	.byte		        c_v-24
	.byte	W01
	.byte		        c_v-26
	.byte	W01
	.byte		VOL   , 58*seq_162_mvl/mxv
	.byte		BEND  , c_v-28
	.byte	W01
	.byte		        c_v-30
	.byte	W01
	.byte		        c_v-32
	.byte	W01
	.byte		VOL   , 58*seq_162_mvl/mxv
	.byte		BEND  , c_v-34
	.byte	W01
	.byte		        c_v-36
	.byte	W01
	.byte		        c_v-38
	.byte	W01
	.byte		VOL   , 57*seq_162_mvl/mxv
	.byte		BEND  , c_v-40
	.byte	W01
	.byte		        c_v-42
	.byte	W01
	.byte		VOL   , 56*seq_162_mvl/mxv
	.byte		BEND  , c_v-44
	.byte	W01
	.byte		VOL   , 54*seq_162_mvl/mxv
	.byte		BEND  , c_v-46
	.byte	W01
	.byte		VOL   , 54*seq_162_mvl/mxv
	.byte		BEND  , c_v-49
	.byte	W01
	.byte		VOL   , 52*seq_162_mvl/mxv
	.byte		BEND  , c_v-52
	.byte	W01
	.byte		VOL   , 51*seq_162_mvl/mxv
	.byte		BEND  , c_v-54
	.byte	W01
	.byte		VOL   , 49*seq_162_mvl/mxv
	.byte		BEND  , c_v-56
	.byte	W01
	.byte		VOL   , 48*seq_162_mvl/mxv
	.byte		BEND  , c_v-58
	.byte	W01
	.byte		VOL   , 47*seq_162_mvl/mxv
	.byte	W01
	.byte		        45*seq_162_mvl/mxv
	.byte		BEND  , c_v-59
	.byte	W01
	.byte		VOL   , 42*seq_162_mvl/mxv
	.byte	W01
	.byte		        38*seq_162_mvl/mxv
	.byte		BEND  , c_v-60
	.byte	W01
	.byte		VOL   , 35*seq_162_mvl/mxv
	.byte	W01
	.byte		        30*seq_162_mvl/mxv
	.byte		BEND  , c_v-61
	.byte	W01
	.byte		VOL   , 26*seq_162_mvl/mxv
	.byte	W01
	.byte		        21*seq_162_mvl/mxv
	.byte		BEND  , c_v-61
	.byte	W01
	.byte		VOL   , 15*seq_162_mvl/mxv
	.byte	W01
	.byte		        10*seq_162_mvl/mxv
	.byte		BEND  , c_v-62
	.byte	W01
	.byte		VOL   , 4*seq_162_mvl/mxv
	.byte	W01
	.byte		        0*seq_162_mvl/mxv
	.byte	W14
	.byte	FINE

@******************************************************@

	.align	2

seq_162:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_162_pri	@ Priority
	.byte	seq_162_rev	@ Reverb

	.word	seq_162_grp

	.word	seq_162_0

	.end
