@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_387_grp, bank_045
	.equ	seq_387_pri, 10
	.equ	seq_387_rev, 0
	.equ	seq_387_mvl, 127
	.equ	seq_387_key, 0

	.section .rodata
	.global	seq_387
	.align	2

@*********************** Track 01 ***********************@

seq_387_0:
	.byte		VOL   , 127*seq_387_mvl/mxv
	.byte	KEYSH , seq_387_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 14
	.byte		N12   , Cn3 , v127
	.byte	W24
	.byte	FINE

@******************************************************@

	.align	2

seq_387:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_387_pri	@ Priority
	.byte	seq_387_rev	@ Reverb

	.word	seq_387_grp

	.word	seq_387_0

	.end
