@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_267_grp, bank_013
	.equ	seq_267_pri, 100
	.equ	seq_267_rev, 0
	.equ	seq_267_mvl, 127
	.equ	seq_267_key, 0

	.section .rodata
	.global	seq_267
	.align	2

@*********************** Track 01 ***********************@

seq_267_0:
	.byte		VOL   , 110*seq_267_mvl/mxv
	.byte	KEYSH , seq_267_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 28
	.byte		N68   , Cn3 , v127
	.byte	W24
	.byte	W24
	.byte	W24
	.byte	FINE

@******************************************************@

	.align	2

seq_267:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_267_pri	@ Priority
	.byte	seq_267_rev	@ Reverb

	.word	seq_267_grp

	.word	seq_267_0

	.end
