@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_223_grp, bank_013
	.equ	seq_223_pri, 100
	.equ	seq_223_rev, 0
	.equ	seq_223_mvl, 127
	.equ	seq_223_key, 0

	.section .rodata
	.global	seq_223
	.align	2

@*********************** Track 01 ***********************@

seq_223_0:
	.byte		VOL   , 115*seq_223_mvl/mxv
	.byte	KEYSH , seq_223_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 24
	.byte		N72   , Cn3 , v127
	.byte	W24
	.byte	W24
	.byte	W24
	.byte	FINE

@******************************************************@

	.align	2

seq_223:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_223_pri	@ Priority
	.byte	seq_223_rev	@ Reverb

	.word	seq_223_grp

	.word	seq_223_0

	.end
