@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_347_grp, bank_013
	.equ	seq_347_pri, 100
	.equ	seq_347_rev, 0
	.equ	seq_347_mvl, 127
	.equ	seq_347_key, 0

	.section .rodata
	.global	seq_347
	.align	2

@*********************** Track 01 ***********************@

seq_347_0:
	.byte	KEYSH , seq_347_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 28
	.byte		VOL   , 95*seq_347_mvl/mxv
	.byte		BEND  , c_v+0
	.byte		N48   , Gn3 , v127
	.byte	W24
	.byte	W24
	.byte	FINE

@******************************************************@

	.align	2

seq_347:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_347_pri	@ Priority
	.byte	seq_347_rev	@ Reverb

	.word	seq_347_grp

	.word	seq_347_0

	.end
