@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_095_grp, bank_044
	.equ	seq_095_pri, 60
	.equ	seq_095_rev, 0
	.equ	seq_095_mvl, 127
	.equ	seq_095_key, 0

	.section .rodata
	.global	seq_095
	.align	2

@*********************** Track 01 ***********************@

seq_095_0:
	.byte		VOL   , 127*seq_095_mvl/mxv
	.byte	KEYSH , seq_095_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 14
	.byte		BENDR , 2
	.byte		BEND  , c_v+5
	.byte		TIE   , Cn3 , v127
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	GOTO
	 .word	seq_095_0 + 0x10
	.byte	FINE

@******************************************************@

	.align	2

seq_095:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_095_pri	@ Priority
	.byte	seq_095_rev	@ Reverb

	.word	seq_095_grp

	.word	seq_095_0

	.end
