@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_178_grp, bank_044
	.equ	seq_178_pri, 10
	.equ	seq_178_rev, 0
	.equ	seq_178_mvl, 127
	.equ	seq_178_key, 0

	.section .rodata
	.global	seq_178
	.align	2

@*********************** Track 01 ***********************@

seq_178_0:
	.byte		VOL   , 100*seq_178_mvl/mxv
	.byte	KEYSH , seq_178_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 88
	.byte		BENDR , 2
	.byte		BEND  , c_v-16
	.byte		N96   , Cn3 , v127
	.byte	W96
	.byte	FINE

@******************************************************@

	.align	2

seq_178:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_178_pri	@ Priority
	.byte	seq_178_rev	@ Reverb

	.word	seq_178_grp

	.word	seq_178_0

	.end
