@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_332_grp, bank_013
	.equ	seq_332_pri, 100
	.equ	seq_332_rev, 0
	.equ	seq_332_mvl, 127
	.equ	seq_332_key, 0

	.section .rodata
	.global	seq_332
	.align	2

@*********************** Track 01 ***********************@

seq_332_0:
	.byte	KEYSH , seq_332_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 12
	.byte		VOL   , 105*seq_332_mvl/mxv
	.byte		BEND  , c_v+0
	.byte		N64   , Fs3 , v127
	.byte	W24
	.byte	W24
	.byte	W24
	.byte	FINE

@******************************************************@

	.align	2

seq_332:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_332_pri	@ Priority
	.byte	seq_332_rev	@ Reverb

	.word	seq_332_grp

	.word	seq_332_0

	.end
