@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_309_grp, bank_013
	.equ	seq_309_pri, 100
	.equ	seq_309_rev, 0
	.equ	seq_309_mvl, 127
	.equ	seq_309_key, 0

	.section .rodata
	.global	seq_309
	.align	2

@*********************** Track 01 ***********************@

seq_309_0:
	.byte	KEYSH , seq_309_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 29
	.byte		VOL   , 100*seq_309_mvl/mxv
	.byte		BENDR , 8
	.byte		BEND  , c_v+0
	.byte		N76   , Gn3 , v127
	.byte	W02
	.byte		BEND  , c_v+0
	.byte	W01
	.byte		VOL   , 98*seq_309_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v-2
	.byte	W01
	.byte		VOL   , 94*seq_309_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v-3
	.byte	W01
	.byte		VOL   , 90*seq_309_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v-4
	.byte	W01
	.byte		VOL   , 86*seq_309_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v-6
	.byte	W01
	.byte		VOL   , 82*seq_309_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v-7
	.byte	W01
	.byte		VOL   , 78*seq_309_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v-8
	.byte	W01
	.byte		VOL   , 74*seq_309_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v-10
	.byte	W01
	.byte		VOL   , 70*seq_309_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v-11
	.byte	W01
	.byte		VOL   , 66*seq_309_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v-12
	.byte	W01
	.byte		VOL   , 62*seq_309_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v-14
	.byte	W01
	.byte		VOL   , 59*seq_309_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v-15
	.byte	W01
	.byte		VOL   , 55*seq_309_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v-16
	.byte	W01
	.byte		VOL   , 51*seq_309_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v-20
	.byte	W01
	.byte		VOL   , 47*seq_309_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v-24
	.byte	W01
	.byte		VOL   , 43*seq_309_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v-28
	.byte	W01
	.byte		VOL   , 39*seq_309_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v-32
	.byte	W01
	.byte		VOL   , 35*seq_309_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v-36
	.byte	W01
	.byte		VOL   , 31*seq_309_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v-40
	.byte	W01
	.byte		VOL   , 27*seq_309_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v-44
	.byte	W01
	.byte		VOL   , 23*seq_309_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v-48
	.byte	W01
	.byte		VOL   , 19*seq_309_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v-52
	.byte	W01
	.byte		VOL   , 15*seq_309_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v-56
	.byte	W01
	.byte		VOL   , 11*seq_309_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v-60
	.byte	W01
	.byte		VOL   , 7*seq_309_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v-64
	.byte	W01
	.byte		VOL   , 3*seq_309_mvl/mxv
	.byte	W03
	.byte		        0*seq_309_mvl/mxv
	.byte	W18
	.byte	FINE

@******************************************************@

	.align	2

seq_309:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_309_pri	@ Priority
	.byte	seq_309_rev	@ Reverb

	.word	seq_309_grp

	.word	seq_309_0

	.end
