@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_207_grp, bank_013
	.equ	seq_207_pri, 100
	.equ	seq_207_rev, 0
	.equ	seq_207_mvl, 127
	.equ	seq_207_key, 0

	.section .rodata
	.global	seq_207
	.align	2

@*********************** Track 01 ***********************@

seq_207_0:
	.byte		VOL   , 115*seq_207_mvl/mxv
	.byte	KEYSH , seq_207_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 7
	.byte		N84   , Cn3 , v127
	.byte	W24
	.byte	W24
	.byte	W24
	.byte	W24
	.byte	FINE

@******************************************************@

	.align	2

seq_207:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_207_pri	@ Priority
	.byte	seq_207_rev	@ Reverb

	.word	seq_207_grp

	.word	seq_207_0

	.end
