@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_196_grp, bank_044
	.equ	seq_196_pri, 10
	.equ	seq_196_rev, 0
	.equ	seq_196_mvl, 127
	.equ	seq_196_key, 0

	.section .rodata
	.global	seq_196
	.align	2

@*********************** Track 01 ***********************@

seq_196_0:
	.byte	KEYSH , seq_196_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 76
	.byte		VOL   , 70*seq_196_mvl/mxv
	.byte		BENDR , 16
	.byte		BEND  , c_v+0
	.byte		N08   , Gn5 , v112
	.byte	W01
	.byte		BEND  , c_v+0
	.byte	W01
	.byte		        c_v+3
	.byte	W01
	.byte		        c_v+7
	.byte	W01
	.byte		        c_v+13
	.byte	W01
	.byte		        c_v+20
	.byte	W01
	.byte		        c_v+29
	.byte	W01
	.byte		        c_v+40
	.byte	W05
	.byte		        c_v+0
	.byte		N12   , Cn6 , v127
	.byte	W12
	.byte	FINE

@*********************** Track 02 ***********************@

seq_196_1:
	.byte	KEYSH , seq_196_key+0
	.byte		VOICE , 77
	.byte		PAN   , c_v+0
	.byte		VOL   , 44*seq_196_mvl/mxv
	.byte		BENDR , 16
	.byte		BEND  , c_v+1
	.byte		N08   , Gn5 , v127
	.byte	W01
	.byte		BEND  , c_v+2
	.byte	W01
	.byte		        c_v+4
	.byte	W01
	.byte		        c_v+8
	.byte	W01
	.byte		        c_v+14
	.byte	W01
	.byte		        c_v+22
	.byte	W01
	.byte		        c_v+31
	.byte	W01
	.byte		        c_v+41
	.byte	W05
	.byte		        c_v+1
	.byte		N12   , Cn6 
	.byte	W12
	.byte	FINE

@******************************************************@

	.align	2

seq_196:
	.byte	2	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_196_pri	@ Priority
	.byte	seq_196_rev	@ Reverb

	.word	seq_196_grp

	.word	seq_196_0
	.word	seq_196_1

	.end
