@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_319_grp, bank_013
	.equ	seq_319_pri, 100
	.equ	seq_319_rev, 0
	.equ	seq_319_mvl, 127
	.equ	seq_319_key, 0

	.section .rodata
	.global	seq_319
	.align	2

@*********************** Track 01 ***********************@

seq_319_0:
	.byte	KEYSH , seq_319_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 35
	.byte		VOL   , 105*seq_319_mvl/mxv
	.byte		BENDR , 8
	.byte		BEND  , c_v-32
	.byte		N24   , Gn3 , v127
	.byte	W03
	.byte		BEND  , c_v-22
	.byte	W03
	.byte		        c_v-4
	.byte	W03
	.byte		        c_v+20
	.byte	W03
	.byte		        c_v+32
	.byte	W03
	.byte		        c_v+29
	.byte	W03
	.byte		        c_v+21
	.byte	W03
	.byte		        c_v+8
	.byte	W03
	.byte		VOL   , 103*seq_319_mvl/mxv
	.byte		BEND  , c_v+3
	.byte	W03
	.byte		        c_v+0
	.byte		N84   , Fn3 
	.byte	W01
	.byte		VOL   , 99*seq_319_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v-4
	.byte	W02
	.byte		VOL   , 95*seq_319_mvl/mxv
	.byte	W01
	.byte		BEND  , c_v-2
	.byte	W03
	.byte		VOL   , 90*seq_319_mvl/mxv
	.byte		BEND  , c_v+2
	.byte	W03
	.byte		        c_v+8
	.byte	W01
	.byte		VOL   , 86*seq_319_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v+16
	.byte	W02
	.byte		VOL   , 82*seq_319_mvl/mxv
	.byte	W01
	.byte		BEND  , c_v+24
	.byte	W03
	.byte		VOL   , 78*seq_319_mvl/mxv
	.byte		BEND  , c_v+27
	.byte	W03
	.byte		        c_v+30
	.byte	W01
	.byte		VOL   , 74*seq_319_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v+32
	.byte	W02
	.byte		VOL   , 70*seq_319_mvl/mxv
	.byte	W04
	.byte		        66*seq_319_mvl/mxv
	.byte		BEND  , c_v+29
	.byte	W03
	.byte		        c_v+27
	.byte	W01
	.byte		VOL   , 62*seq_319_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v+25
	.byte	W02
	.byte		VOL   , 57*seq_319_mvl/mxv
	.byte	W01
	.byte		BEND  , c_v+21
	.byte	W03
	.byte		VOL   , 53*seq_319_mvl/mxv
	.byte		BEND  , c_v+16
	.byte	W03
	.byte		        c_v+12
	.byte	W01
	.byte		VOL   , 49*seq_319_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v+7
	.byte	W02
	.byte		VOL   , 45*seq_319_mvl/mxv
	.byte	W01
	.byte		BEND  , c_v+3
	.byte	W03
	.byte		VOL   , 41*seq_319_mvl/mxv
	.byte		BEND  , c_v-2
	.byte	W03
	.byte		        c_v-7
	.byte	W01
	.byte		VOL   , 37*seq_319_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v-12
	.byte	W02
	.byte		VOL   , 33*seq_319_mvl/mxv
	.byte	W01
	.byte		BEND  , c_v-18
	.byte	W03
	.byte		VOL   , 28*seq_319_mvl/mxv
	.byte		BEND  , c_v-25
	.byte	W03
	.byte		        c_v-33
	.byte	W01
	.byte		VOL   , 24*seq_319_mvl/mxv
	.byte	W02
	.byte		BEND  , c_v-41
	.byte	W02
	.byte		VOL   , 20*seq_319_mvl/mxv
	.byte	W01
	.byte		BEND  , c_v-48
	.byte	W03
	.byte		VOL   , 16*seq_319_mvl/mxv
	.byte		BEND  , c_v-54
	.byte	W12
	.byte	FINE

@******************************************************@

	.align	2

seq_319:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_319_pri	@ Priority
	.byte	seq_319_rev	@ Reverb

	.word	seq_319_grp

	.word	seq_319_0

	.end
