@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_341_grp, bank_013
	.equ	seq_341_pri, 100
	.equ	seq_341_rev, 0
	.equ	seq_341_mvl, 127
	.equ	seq_341_key, 0

	.section .rodata
	.global	seq_341
	.align	2

@*********************** Track 01 ***********************@

seq_341_0:
	.byte	KEYSH , seq_341_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 21
	.byte		VOL   , 100*seq_341_mvl/mxv
	.byte		BEND  , c_v+0
	.byte		N48   , Gs3 , v127
	.byte	W24
	.byte	W24
	.byte	FINE

@******************************************************@

	.align	2

seq_341:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_341_pri	@ Priority
	.byte	seq_341_rev	@ Reverb

	.word	seq_341_grp

	.word	seq_341_0

	.end
