@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_076_grp, bank_043
	.equ	seq_076_pri, 50
	.equ	seq_076_rev, 0
	.equ	seq_076_mvl, 127
	.equ	seq_076_key, 0

	.section .rodata
	.global	seq_076
	.align	2

@*********************** Track 01 ***********************@

seq_076_0:
	.byte		VOL   , 110*seq_076_mvl/mxv
	.byte	KEYSH , seq_076_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 6
	.byte		TIE   , Cn3 , v127
	.byte	W48
	.byte	W48
	.byte	W48
	.byte	GOTO
	 .word	seq_076_0 + 0xC
	.byte	FINE

@******************************************************@

	.align	2

seq_076:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_076_pri	@ Priority
	.byte	seq_076_rev	@ Reverb

	.word	seq_076_grp

	.word	seq_076_0

	.end
