@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_133_grp, bank_044
	.equ	seq_133_pri, 30
	.equ	seq_133_rev, 0
	.equ	seq_133_mvl, 127
	.equ	seq_133_key, 0

	.section .rodata
	.global	seq_133
	.align	2

@*********************** Track 01 ***********************@

seq_133_0:
	.byte		VOL   , 100*seq_133_mvl/mxv
	.byte	KEYSH , seq_133_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 117
	.byte		BENDR , 36
	.byte		BEND  , c_v-47
	.byte		N28   , Cn3 , v127
	.byte	W01
	.byte		BEND  , c_v-40
	.byte	W01
	.byte		        c_v-32
	.byte	W01
	.byte		        c_v-24
	.byte	W01
	.byte		        c_v-16
	.byte	W01
	.byte		        c_v-8
	.byte	W01
	.byte		        c_v+0
	.byte	W01
	.byte		        c_v+7
	.byte	W01
	.byte		        c_v+15
	.byte	W01
	.byte		        c_v+23
	.byte	W01
	.byte		        c_v-32
	.byte	W01
	.byte		        c_v-24
	.byte	W01
	.byte		        c_v-16
	.byte	W01
	.byte		        c_v-8
	.byte	W01
	.byte		        c_v+0
	.byte	W01
	.byte		        c_v+7
	.byte	W01
	.byte		        c_v+15
	.byte	W01
	.byte		        c_v+23
	.byte	W01
	.byte		        c_v+31
	.byte	W01
	.byte		        c_v-16
	.byte	W01
	.byte		        c_v-8
	.byte	W01
	.byte		        c_v+0
	.byte	W01
	.byte		        c_v+7
	.byte	W01
	.byte		        c_v+15
	.byte	W01
	.byte		        c_v+23
	.byte	W01
	.byte		        c_v+31
	.byte	W01
	.byte		        c_v+39
	.byte	W01
	.byte		        c_v+46
	.byte	W21
	.byte	FINE

@******************************************************@

	.align	2

seq_133:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_133_pri	@ Priority
	.byte	seq_133_rev	@ Reverb

	.word	seq_133_grp

	.word	seq_133_0

	.end
