@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_357_grp, bank_013
	.equ	seq_357_pri, 100
	.equ	seq_357_rev, 0
	.equ	seq_357_mvl, 127
	.equ	seq_357_key, 0

	.section .rodata
	.global	seq_357
	.align	2

@*********************** Track 01 ***********************@

seq_357_0:
	.byte		VOL   , 110*seq_357_mvl/mxv
	.byte	KEYSH , seq_357_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 35
	.byte		N68   , Gn3 , v127
	.byte	W24
	.byte	W24
	.byte	W24
	.byte	FINE

@******************************************************@

	.align	2

seq_357:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_357_pri	@ Priority
	.byte	seq_357_rev	@ Reverb

	.word	seq_357_grp

	.word	seq_357_0

	.end
