@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_199_grp, bank_044
	.equ	seq_199_pri, 30
	.equ	seq_199_rev, 0
	.equ	seq_199_mvl, 127
	.equ	seq_199_key, 0

	.section .rodata
	.global	seq_199
	.align	2

@*********************** Track 01 ***********************@

seq_199_0:
	.byte	KEYSH , seq_199_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 38
	.byte		BENDR , 1
	.byte		VOL   , 95*seq_199_mvl/mxv
	.byte		BEND  , c_v+16
	.byte		N14   , Cn2 , v127
	.byte	W16
	.byte		N04
	.byte	W08
	.byte		N14
	.byte	W16
	.byte		N04
	.byte	W08
	.byte	FINE

@*********************** Track 02 ***********************@

seq_199_1:
	.byte	KEYSH , seq_199_key+0
	.byte		VOICE , 39
	.byte		VOL   , 71*seq_199_mvl/mxv
	.byte		N14   , Cn2 , v127
	.byte	W16
	.byte		N04
	.byte	W08
	.byte		N14
	.byte	W16
	.byte		N04
	.byte	W08
	.byte	FINE

@******************************************************@

	.align	2

seq_199:
	.byte	2	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_199_pri	@ Priority
	.byte	seq_199_rev	@ Reverb

	.word	seq_199_grp

	.word	seq_199_0
	.word	seq_199_1

	.end
