@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_254_grp, bank_013
	.equ	seq_254_pri, 100
	.equ	seq_254_rev, 0
	.equ	seq_254_mvl, 127
	.equ	seq_254_key, 0

	.section .rodata
	.global	seq_254
	.align	2

@*********************** Track 01 ***********************@

seq_254_0:
	.byte	KEYSH , seq_254_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 13
	.byte		VOL   , 104*seq_254_mvl/mxv
	.byte		BENDR , 5
	.byte		BEND  , c_v+0
	.byte		N72   , Cn3 , v127
	.byte	W07
	.byte		VOL   , 104*seq_254_mvl/mxv
	.byte		BEND  , c_v+0
	.byte	W02
	.byte		        c_v-2
	.byte	W02
	.byte		VOL   , 97*seq_254_mvl/mxv
	.byte		BEND  , c_v-4
	.byte	W02
	.byte		        c_v-6
	.byte	W02
	.byte		VOL   , 90*seq_254_mvl/mxv
	.byte		BEND  , c_v-8
	.byte	W02
	.byte		        c_v-10
	.byte	W02
	.byte		VOL   , 84*seq_254_mvl/mxv
	.byte		BEND  , c_v-12
	.byte	W02
	.byte		        c_v-14
	.byte	W02
	.byte		VOL   , 77*seq_254_mvl/mxv
	.byte		BEND  , c_v-16
	.byte	W01
	.byte	W01
	.byte		        c_v-18
	.byte	W02
	.byte		VOL   , 71*seq_254_mvl/mxv
	.byte		BEND  , c_v-20
	.byte	W02
	.byte		        c_v-22
	.byte	W02
	.byte		VOL   , 64*seq_254_mvl/mxv
	.byte		BEND  , c_v-24
	.byte	W02
	.byte		        c_v-26
	.byte	W02
	.byte		VOL   , 58*seq_254_mvl/mxv
	.byte		BEND  , c_v-28
	.byte	W02
	.byte		        c_v-30
	.byte	W02
	.byte		VOL   , 51*seq_254_mvl/mxv
	.byte		BEND  , c_v-32
	.byte	W02
	.byte		        c_v-34
	.byte	W02
	.byte		VOL   , 45*seq_254_mvl/mxv
	.byte		BEND  , c_v-36
	.byte	W02
	.byte		        c_v-38
	.byte	W02
	.byte		VOL   , 38*seq_254_mvl/mxv
	.byte		BEND  , c_v-40
	.byte	W01
	.byte	W01
	.byte		        c_v-42
	.byte	W02
	.byte		VOL   , 31*seq_254_mvl/mxv
	.byte		BEND  , c_v-44
	.byte	W02
	.byte		        c_v-46
	.byte	W02
	.byte		VOL   , 25*seq_254_mvl/mxv
	.byte		BEND  , c_v-48
	.byte	W02
	.byte		        c_v-50
	.byte	W02
	.byte		VOL   , 18*seq_254_mvl/mxv
	.byte		BEND  , c_v-52
	.byte	W02
	.byte		        c_v-54
	.byte	W02
	.byte		VOL   , 12*seq_254_mvl/mxv
	.byte		BEND  , c_v-56
	.byte	W02
	.byte		        c_v-58
	.byte	W02
	.byte		VOL   , 6*seq_254_mvl/mxv
	.byte		BEND  , c_v-60
	.byte	W02
	.byte		        c_v-62
	.byte	W02
	.byte		        c_v-64
	.byte	W01
	.byte	FINE

@******************************************************@

	.align	2

seq_254:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_254_pri	@ Priority
	.byte	seq_254_rev	@ Reverb

	.word	seq_254_grp

	.word	seq_254_0

	.end
