@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_174_grp, bank_044
	.equ	seq_174_pri, 20
	.equ	seq_174_rev, 0
	.equ	seq_174_mvl, 127
	.equ	seq_174_key, 0

	.section .rodata
	.global	seq_174
	.align	2

@*********************** Track 01 ***********************@

seq_174_0:
	.byte	KEYSH , seq_174_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 123
	.byte		BENDR , 24
	.byte		VOL   , 20*seq_174_mvl/mxv
	.byte		BEND  , c_v+0
	.byte		TIE   , En6 , v127
	.byte	W02
	.byte		BEND  , c_v-2
	.byte	W02
	.byte		        c_v-3
	.byte	W02
	.byte		        c_v-4
	.byte	W02
	.byte		        c_v-6
	.byte	W02
	.byte		        c_v-7
	.byte	W02
	.byte		        c_v-8
	.byte	W02
	.byte		        c_v-10
	.byte	W02
	.byte		        c_v-11
	.byte	W02
	.byte		        c_v-12
	.byte	W02
	.byte		        c_v-14
	.byte	W02
	.byte		        c_v-15
	.byte	W02
	.byte		        c_v-16
	.byte	W02
	.byte		        c_v-17
	.byte	W02
	.byte		        c_v-19
	.byte	W02
	.byte		        c_v-20
	.byte	W02
	.byte		VOL   , 50*seq_174_mvl/mxv
	.byte		BEND  , c_v-21
	.byte	W02
	.byte		        c_v-23
	.byte	W02
	.byte		        c_v-24
	.byte	W02
	.byte		        c_v-25
	.byte	W02
	.byte		        c_v-27
	.byte	W02
	.byte		        c_v-28
	.byte	W02
	.byte		        c_v-29
	.byte	W02
	.byte		        c_v-31
	.byte	W02
	.byte		        c_v-32
	.byte	W02
	.byte		        c_v-33
	.byte	W02
	.byte		        c_v-34
	.byte	W02
	.byte		        c_v-36
	.byte	W02
	.byte		        c_v-37
	.byte	W02
	.byte		        c_v-38
	.byte	W02
	.byte		        c_v-40
	.byte	W02
	.byte		        c_v-41
	.byte	W02
	.byte		VOL   , 90*seq_174_mvl/mxv
	.byte		BEND  , c_v-42
	.byte	W02
	.byte		        c_v-44
	.byte	W02
	.byte		        c_v-45
	.byte	W02
	.byte		        c_v-46
	.byte	W02
	.byte		        c_v-47
	.byte	W02
	.byte		        c_v-49
	.byte	W02
	.byte		        c_v-50
	.byte	W02
	.byte		        c_v-51
	.byte	W02
	.byte		        c_v-53
	.byte	W02
	.byte		        c_v-54
	.byte	W02
	.byte		        c_v-55
	.byte	W02
	.byte		        c_v-57
	.byte	W02
	.byte		        c_v-58
	.byte	W02
	.byte		        c_v-59
	.byte	W02
	.byte		        c_v-61
	.byte	W02
	.byte		        c_v-62
	.byte	W02
	.byte		VOL   , 127*seq_174_mvl/mxv
	.byte		BEND  , c_v-63
	.byte	W02
	.byte		        c_v-64
	.byte	W01
	.byte		EOT
	.byte	W44
	.byte	W01
	.byte	FINE

@******************************************************@

	.align	2

seq_174:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_174_pri	@ Priority
	.byte	seq_174_rev	@ Reverb

	.word	seq_174_grp

	.word	seq_174_0

	.end
