@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_081_grp, bank_043
	.equ	seq_081_pri, 50
	.equ	seq_081_rev, 0
	.equ	seq_081_mvl, 127
	.equ	seq_081_key, 0

	.section .rodata
	.global	seq_081
	.align	2

@*********************** Track 01 ***********************@

seq_081_0:
	.byte		VOL   , 127*seq_081_mvl/mxv
	.byte	KEYSH , seq_081_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 10
	.byte		N05   , Gn2 , v127
	.byte	W24
	.byte	W24
	.byte	FINE

@******************************************************@

	.align	2

seq_081:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_081_pri	@ Priority
	.byte	seq_081_rev	@ Reverb

	.word	seq_081_grp

	.word	seq_081_0

	.end
