@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_276_grp, bank_013
	.equ	seq_276_pri, 100
	.equ	seq_276_rev, 0
	.equ	seq_276_mvl, 127
	.equ	seq_276_key, 0

	.section .rodata
	.global	seq_276
	.align	2

@*********************** Track 01 ***********************@

seq_276_0:
	.byte		VOL   , 108*seq_276_mvl/mxv
	.byte	KEYSH , seq_276_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 35
	.byte		N15   , Cs3 , v127
	.byte	W18
	.byte		N90
	.byte	W06
	.byte	W11
	.byte		BEND  , c_v-4
	.byte	W04
	.byte		        c_v-2
	.byte	W04
	.byte		        c_v+2
	.byte	W04
	.byte		        c_v+7
	.byte	W01
	.byte	W02
	.byte		        c_v+10
	.byte	W04
	.byte		        c_v+14
	.byte	W04
	.byte		        c_v+20
	.byte	W04
	.byte		        c_v+24
	.byte	W08
	.byte		        c_v+20
	.byte	W02
	.byte	W01
	.byte		        c_v+16
	.byte	W04
	.byte		        c_v+10
	.byte	W04
	.byte		        c_v+2
	.byte	W04
	.byte		        c_v-4
	.byte	W04
	.byte		        c_v-4
	.byte	W03
	.byte		        c_v+0
	.byte	W04
	.byte	W24
	.byte	FINE

@******************************************************@

	.align	2

seq_276:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_276_pri	@ Priority
	.byte	seq_276_rev	@ Reverb

	.word	seq_276_grp

	.word	seq_276_0

	.end
