@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_168_grp, bank_044
	.equ	seq_168_pri, 10
	.equ	seq_168_rev, 0
	.equ	seq_168_mvl, 127
	.equ	seq_168_key, 0

	.section .rodata
	.global	seq_168
	.align	2

@*********************** Track 01 ***********************@

seq_168_0:
	.byte		VOL   , 115*seq_168_mvl/mxv
	.byte	KEYSH , seq_168_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 82
	.byte		N18   , Cn3 , v127
	.byte	W24
	.byte	FINE

@******************************************************@

	.align	2

seq_168:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_168_pri	@ Priority
	.byte	seq_168_rev	@ Reverb

	.word	seq_168_grp

	.word	seq_168_0

	.end
