@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_170_grp, bank_044
	.equ	seq_170_pri, 10
	.equ	seq_170_rev, 0
	.equ	seq_170_mvl, 127
	.equ	seq_170_key, 0

	.section .rodata
	.global	seq_170
	.align	2

@*********************** Track 01 ***********************@

seq_170_0:
	.byte		VOL   , 127*seq_170_mvl/mxv
	.byte	KEYSH , seq_170_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 84
	.byte		N19   , Cn3 , v127
	.byte	W24
	.byte	FINE

@******************************************************@

	.align	2

seq_170:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_170_pri	@ Priority
	.byte	seq_170_rev	@ Reverb

	.word	seq_170_grp

	.word	seq_170_0

	.end
