@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_184_grp, bank_044
	.equ	seq_184_pri, 60
	.equ	seq_184_rev, 0
	.equ	seq_184_mvl, 127
	.equ	seq_184_key, 0

	.section .rodata
	.global	seq_184
	.align	2

@*********************** Track 01 ***********************@

seq_184_0:
	.byte	KEYSH , seq_184_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 13
	.byte		VOL   , 76*seq_184_mvl/mxv
	.byte		BENDR , 2
	.byte		BEND  , c_v+38
	.byte		N30   , Dn4 , v127
	.byte	W01
	.byte		VOL   , 106*seq_184_mvl/mxv
	.byte		BEND  , c_v+37
	.byte	W01
	.byte		VOL   , 127*seq_184_mvl/mxv
	.byte		BEND  , c_v+36
	.byte	W01
	.byte		VOL   , 126*seq_184_mvl/mxv
	.byte		BEND  , c_v+36
	.byte	W01
	.byte		VOL   , 121*seq_184_mvl/mxv
	.byte		BEND  , c_v+35
	.byte	W01
	.byte		VOL   , 116*seq_184_mvl/mxv
	.byte		BEND  , c_v+35
	.byte	W01
	.byte		VOL   , 112*seq_184_mvl/mxv
	.byte		BEND  , c_v+34
	.byte	W01
	.byte		VOL   , 107*seq_184_mvl/mxv
	.byte		BEND  , c_v+34
	.byte	W01
	.byte		VOL   , 102*seq_184_mvl/mxv
	.byte		BEND  , c_v+33
	.byte	W01
	.byte		VOL   , 98*seq_184_mvl/mxv
	.byte		BEND  , c_v+33
	.byte	W01
	.byte		VOL   , 93*seq_184_mvl/mxv
	.byte		BEND  , c_v+32
	.byte	W01
	.byte		VOL   , 89*seq_184_mvl/mxv
	.byte		BEND  , c_v+31
	.byte	W01
	.byte		VOL   , 84*seq_184_mvl/mxv
	.byte		BEND  , c_v+31
	.byte	W01
	.byte		VOL   , 79*seq_184_mvl/mxv
	.byte		BEND  , c_v+30
	.byte	W01
	.byte		VOL   , 75*seq_184_mvl/mxv
	.byte		BEND  , c_v+30
	.byte	W01
	.byte		VOL   , 70*seq_184_mvl/mxv
	.byte		BEND  , c_v+29
	.byte	W01
	.byte		VOL   , 66*seq_184_mvl/mxv
	.byte		BEND  , c_v+29
	.byte	W01
	.byte		VOL   , 61*seq_184_mvl/mxv
	.byte		BEND  , c_v+28
	.byte	W01
	.byte		VOL   , 56*seq_184_mvl/mxv
	.byte		BEND  , c_v+28
	.byte	W01
	.byte		VOL   , 52*seq_184_mvl/mxv
	.byte		BEND  , c_v+27
	.byte	W01
	.byte		VOL   , 47*seq_184_mvl/mxv
	.byte		BEND  , c_v+26
	.byte	W01
	.byte		VOL   , 43*seq_184_mvl/mxv
	.byte		BEND  , c_v+26
	.byte	W01
	.byte		VOL   , 38*seq_184_mvl/mxv
	.byte		BEND  , c_v+25
	.byte	W01
	.byte		VOL   , 33*seq_184_mvl/mxv
	.byte		BEND  , c_v+25
	.byte	W01
	.byte		VOL   , 29*seq_184_mvl/mxv
	.byte		BEND  , c_v+24
	.byte	W01
	.byte		VOL   , 24*seq_184_mvl/mxv
	.byte		BEND  , c_v+24
	.byte	W01
	.byte		VOL   , 19*seq_184_mvl/mxv
	.byte		BEND  , c_v+23
	.byte	W01
	.byte		VOL   , 15*seq_184_mvl/mxv
	.byte		BEND  , c_v+23
	.byte	W01
	.byte		VOL   , 10*seq_184_mvl/mxv
	.byte		BEND  , c_v+22
	.byte	W01
	.byte		VOL   , 6*seq_184_mvl/mxv
	.byte		BEND  , c_v+22
	.byte	W19
	.byte	FINE

@******************************************************@

	.align	2

seq_184:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_184_pri	@ Priority
	.byte	seq_184_rev	@ Reverb

	.word	seq_184_grp

	.word	seq_184_0

	.end
