@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_190_grp, bank_044
	.equ	seq_190_pri, 30
	.equ	seq_190_rev, 0
	.equ	seq_190_mvl, 127
	.equ	seq_190_key, 0

	.section .rodata
	.global	seq_190
	.align	2

@*********************** Track 01 ***********************@

seq_190_0:
	.byte	KEYSH , seq_190_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 73
	.byte		VOL   , 80*seq_190_mvl/mxv
	.byte		N01   , Cn3 , v127
	.byte	W02
	.byte		N04   , Fn4 , v080
	.byte	W22
	.byte	FINE

@******************************************************@

	.align	2

seq_190:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_190_pri	@ Priority
	.byte	seq_190_rev	@ Reverb

	.word	seq_190_grp

	.word	seq_190_0

	.end
