@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_130_grp, bank_044
	.equ	seq_130_pri, 25
	.equ	seq_130_rev, 0
	.equ	seq_130_mvl, 127
	.equ	seq_130_key, 0

	.section .rodata
	.global	seq_130
	.align	2

@*********************** Track 01 ***********************@

seq_130_0:
	.byte		VOL   , 45*seq_130_mvl/mxv
	.byte	KEYSH , seq_130_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 107
	.byte		N04   , Cn4 , v100
	.byte	W04
	.byte		N08   , Fn4 , v127
	.byte	W20
	.byte	FINE

@*********************** Track 02 ***********************@

seq_130_1:
	.byte		VOL   , 45*seq_130_mvl/mxv
	.byte	KEYSH , seq_130_key+0
	.byte		VOICE , 108
	.byte		BENDR , 2
	.byte		BEND  , c_v-6
	.byte		N04   , Cn4 , v064
	.byte	W04
	.byte		N06   , Fn4 
	.byte	W20
	.byte	FINE

@******************************************************@

	.align	2

seq_130:
	.byte	2	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_130_pri	@ Priority
	.byte	seq_130_rev	@ Reverb

	.word	seq_130_grp

	.word	seq_130_0
	.word	seq_130_1

	.end
