@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_100_grp, bank_044
	.equ	seq_100_pri, 60
	.equ	seq_100_rev, 0
	.equ	seq_100_mvl, 127
	.equ	seq_100_key, 0

	.section .rodata
	.global	seq_100
	.align	2

@*********************** Track 01 ***********************@

seq_100_0:
	.byte		VOL   , 80*seq_100_mvl/mxv
	.byte	KEYSH , seq_100_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 17
	.byte		N16   , Cn3 , v127
	.byte	W24
	.byte	FINE

@******************************************************@

	.align	2

seq_100:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_100_pri	@ Priority
	.byte	seq_100_rev	@ Reverb

	.word	seq_100_grp

	.word	seq_100_0

	.end
