@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_159_grp, bank_044
	.equ	seq_159_pri, 10
	.equ	seq_159_rev, 0
	.equ	seq_159_mvl, 127
	.equ	seq_159_key, 0

	.section .rodata
	.global	seq_159
	.align	2

@*********************** Track 01 ***********************@

seq_159_0:
	.byte		VOL   , 120*seq_159_mvl/mxv
	.byte	KEYSH , seq_159_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 85
	.byte		N19   , Cn3 , v127
	.byte	W24
	.byte	FINE

@******************************************************@

	.align	2

seq_159:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_159_pri	@ Priority
	.byte	seq_159_rev	@ Reverb

	.word	seq_159_grp

	.word	seq_159_0

	.end
