@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_246_grp, bank_013
	.equ	seq_246_pri, 100
	.equ	seq_246_rev, 0
	.equ	seq_246_mvl, 127
	.equ	seq_246_key, 0

	.section .rodata
	.global	seq_246
	.align	2

@*********************** Track 01 ***********************@

seq_246_0:
	.byte		VOL   , 110*seq_246_mvl/mxv
	.byte	KEYSH , seq_246_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 6
	.byte		N84   , Cn3 , v127
	.byte	W24
	.byte	W24
	.byte	W24
	.byte	W24
	.byte	FINE

@******************************************************@

	.align	2

seq_246:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_246_pri	@ Priority
	.byte	seq_246_rev	@ Reverb

	.word	seq_246_grp

	.word	seq_246_0

	.end
