@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_217_grp, bank_013
	.equ	seq_217_pri, 100
	.equ	seq_217_rev, 0
	.equ	seq_217_mvl, 127
	.equ	seq_217_key, 0

	.section .rodata
	.global	seq_217
	.align	2

@*********************** Track 01 ***********************@

seq_217_0:
	.byte		VOL   , 127*seq_217_mvl/mxv
	.byte	KEYSH , seq_217_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 17
	.byte		N96   , Cn3 , v127
	.byte	W24
	.byte	W24
	.byte	W24
	.byte	W24
	.byte	FINE

@******************************************************@

	.align	2

seq_217:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_217_pri	@ Priority
	.byte	seq_217_rev	@ Reverb

	.word	seq_217_grp

	.word	seq_217_0

	.end
