@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_301_grp, bank_013
	.equ	seq_301_pri, 100
	.equ	seq_301_rev, 0
	.equ	seq_301_mvl, 127
	.equ	seq_301_key, 0

	.section .rodata
	.global	seq_301
	.align	2

@*********************** Track 01 ***********************@

seq_301_0:
	.byte	KEYSH , seq_301_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 21
	.byte		VOL   , 110*seq_301_mvl/mxv
	.byte		BEND  , c_v+0
	.byte		N48   , Gs3 , v127
	.byte	W24
	.byte	W24
	.byte	FINE

@******************************************************@

	.align	2

seq_301:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_301_pri	@ Priority
	.byte	seq_301_rev	@ Reverb

	.word	seq_301_grp

	.word	seq_301_0

	.end
