@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_093_grp, bank_044
	.equ	seq_093_pri, 60
	.equ	seq_093_rev, 0
	.equ	seq_093_mvl, 127
	.equ	seq_093_key, 0

	.section .rodata
	.global	seq_093
	.align	2

@*********************** Track 01 ***********************@

seq_093_0:
	.byte		VOL   , 127*seq_093_mvl/mxv
	.byte	KEYSH , seq_093_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 15
	.byte		BEND  , c_v+0
	.byte		TIE   , Cn3 , v127
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	GOTO
	 .word	seq_093_0 + 0xE
	.byte	W96
	.byte		EOT   , Cn3 
	.byte	W96
	.byte	FINE

@******************************************************@

	.align	2

seq_093:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_093_pri	@ Priority
	.byte	seq_093_rev	@ Reverb

	.word	seq_093_grp

	.word	seq_093_0

	.end
