@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_091_grp, bank_044
	.equ	seq_091_pri, 60
	.equ	seq_091_rev, 0
	.equ	seq_091_mvl, 127
	.equ	seq_091_key, 0

	.section .rodata
	.global	seq_091
	.align	2

@*********************** Track 01 ***********************@

seq_091_0:
	.byte		VOL   , 127*seq_091_mvl/mxv
	.byte	KEYSH , seq_091_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 13
	.byte		BEND  , c_v+0
	.byte		TIE   , Cn3 , v127
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	GOTO
	 .word	seq_091_0 + 0xE
	.byte	FINE

@******************************************************@

	.align	2

seq_091:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_091_pri	@ Priority
	.byte	seq_091_rev	@ Reverb

	.word	seq_091_grp

	.word	seq_091_0

	.end
