@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	seq_181_grp, bank_044
	.equ	seq_181_pri, 10
	.equ	seq_181_rev, 0
	.equ	seq_181_mvl, 127
	.equ	seq_181_key, 0

	.section .rodata
	.global	seq_181
	.align	2

@*********************** Track 01 ***********************@

seq_181_0:
	.byte		VOL   , 100*seq_181_mvl/mxv
	.byte	KEYSH , seq_181_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 60
	.byte		N32   , Cn3 , v127
	.byte	W24
	.byte	W24
	.byte	FINE

@******************************************************@

	.align	2

seq_181:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	seq_181_pri	@ Priority
	.byte	seq_181_rev	@ Reverb

	.word	seq_181_grp

	.word	seq_181_0

	.end
