@ File generated by m4a2s Song-Module
	.include "MPlayDef.s"

	.equ	song_horn_wario_grp, bank_044
	.equ	song_horn_wario_pri, 10
	.equ	song_horn_wario_rev, 0
	.equ	song_horn_wario_mvl, 127
	.equ	song_horn_wario_key, 0

	.section .rodata
	.global	song_horn_wario
	.align	2

@*********************** Track 01 ***********************@

song_horn_wario_0:
	.byte		VOL   , 110*song_horn_wario_mvl/mxv
	.byte	KEYSH , song_horn_wario_key+0
	.byte	TEMPO , 150/2
	.byte		VOICE , 25
	.byte		N36   , Cn3 , v127
	.byte	W48
	.byte	FINE

@******************************************************@

	.align	2

song_horn_wario:
	.byte	1	@ NumTrks
	.byte	0	@ NumBlks
	.byte	song_horn_wario_pri	@ Priority
	.byte	song_horn_wario_rev	@ Reverb

	.word	song_horn_wario_grp

	.word	song_horn_wario_0

	.end
